from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="secauditai",
    version="0.1.0",
    author="Parthasarathi7722",
    author_email="your.email@example.com",
    description="A powerful CLI security audit tool with AI-powered analysis",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/Parthasarathi7722/secauditai",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: System Administrators",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Security",
        "Topic :: Software Development :: Quality Assurance",
    ],
    python_requires=">=3.8",
    install_requires=[
        "click>=8.0.0",
        "pyyaml>=6.0",
        "rich>=10.0.0",
        "inquirer>=3.0.0",
        "pydantic>=2.0.0",
        "python-dotenv>=0.19.0",
        "tqdm>=4.65.0",
        "requests>=2.31.0",
        "typing-extensions>=4.5.0",
        "schedule>=1.2.0",
        "boto3>=1.26.0",
        "azure-identity>=1.12.0",
        "google-cloud-storage>=2.0.0",
        "kubernetes>=24.0.0",
        "ollama>=0.1.0",
        "transformers>=4.30.0",
        "torch>=2.0.0",
        "scikit-learn>=1.0.0",
        "tree-sitter>=0.20.0",
        "syft>=0.60.0",
        "grype>=0.60.0",
        "jinja2>=3.0.0",
        "pdfkit>=1.0.0",
        "slack-sdk>=3.20.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-cov>=4.0.0",
            "black>=23.0.0",
            "flake8>=6.0.0",
            "mypy>=1.0.0",
            "isort>=5.0.0",
        ],
        "security": [
            "prowler>=3.0.0",
            "cloud-custodian>=0.9.0",
            "dependency-check>=8.0.0",
            "openscap>=1.3.0",
            "inspec>=5.0.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "secauditai=secauditai.cli:main",
        ],
    },
) 